package codegen

import (
	"fmt"
	"strings"
)

func Render(name string, data map[string]interface{}) (string, error) {
	fn, ok := Templates[name]
	if !ok {
		return fmt.Sprintf("// TODO: implement %s\n", name), nil
	}
	return fn(data), nil
}

func appName(d map[string]interface{}) string    { return d["AppName"].(string) }
func desc(d map[string]interface{}) string       { return d["Description"].(string) }
func hasAuth(d map[string]interface{}) bool      { return d["HasAuth"].(bool) }
func entities(d map[string]interface{}) []string { return d["Entities"].([]string) }
func pkg(d map[string]interface{}) string        { return d["Package"].(string) }

func formatFeatures(features []string) string {
	if len(features) == 0 { return "- Core functionality\n" }
	var sb strings.Builder
	for _, f := range features { sb.WriteString("- " + strings.Title(f) + "\n") }
	return sb.String()
}

var Templates = map[string]func(map[string]interface{}) string{

	"readme": func(d map[string]interface{}) string {
		return fmt.Sprintf("# %s\n\n%s\n\n## Generated by NEXUS\n\n## Features\n%s",
			appName(d), desc(d), formatFeatures(d["Features"].([]string)))
	},

	"python_empty": func(d map[string]interface{}) string { return "" },

	"gitignore_python": func(d map[string]interface{}) string {
		return "__pycache__/\n*.pyc\n.env\n.venv/\nvenv/\n.pytest_cache/\napp.db\n"
	},

	"gitignore_go": func(d map[string]interface{}) string {
		return "bin/\n*.exe\n*.test\n.env\n*.db\n"
	},

	"gitignore_node": func(d map[string]interface{}) string {
		return "node_modules/\ndist/\n.env\n*.local\n"
	},

	"gitignore_android": func(d map[string]interface{}) string {
		return "*.iml\n.gradle/\nlocal.properties\n.idea/\n.DS_Store\nbuild/\n"
	},

	"gitignore_flutter": func(d map[string]interface{}) string {
		return ".dart_tool/\n.flutter-plugins\n.flutter-plugins-dependencies\nbuild/\n"
	},

	"python_fastapi_main": func(d map[string]interface{}) string {
		authImport, authMount := "", ""
		if hasAuth(d) {
			authImport = "from src.auth.jwt import auth_router\n"
			authMount  = "app.include_router(auth_router)\n"
		}
		var sb strings.Builder
		sb.WriteString("from fastapi import FastAPI\n")
		sb.WriteString("from fastapi.middleware.cors import CORSMiddleware\n")
		sb.WriteString("from src.api.routes import router\n")
		sb.WriteString("from src.db.database import init_db\n")
		sb.WriteString(authImport)
		sb.WriteString("\napp = FastAPI(title=\"" + appName(d) + "\", version=\"1.0.0\")\n")
		sb.WriteString("app.add_middleware(CORSMiddleware, allow_origins=[\"*\"], allow_methods=[\"*\"], allow_headers=[\"*\"])\n")
		sb.WriteString(authMount)
		sb.WriteString("app.include_router(router, prefix=\"/api/v1\")\n")
		sb.WriteString("\n@app.on_event(\"startup\")\nasync def startup():\n    await init_db()\n")
		sb.WriteString("\n@app.get(\"/health\")\nasync def health():\n    return {\"status\": \"ok\", \"app\": \"" + appName(d) + "\"}\n")
		sb.WriteString("\nif __name__ == \"__main__\":\n    import uvicorn\n    uvicorn.run(\"main:app\", host=\"0.0.0.0\", port=8000, reload=True)\n")
		return sb.String()
	},

	"python_requirements": func(d map[string]interface{}) string {
		base := "fastapi>=0.110.0\nuvicorn[standard]>=0.29.0\npydantic>=2.0.0\nsqlalchemy>=2.0.0\naiosqlite>=0.20.0\npython-dotenv>=1.0.0\nhttpx>=0.27.0\npytest>=8.0.0\npytest-asyncio>=0.23.0\n"
		if hasAuth(d) { base += "python-jose[cryptography]>=3.3.0\npasslib[bcrypt]>=1.7.4\npython-multipart>=0.0.9\n" }
		return base
	},

	"python_routes": func(d map[string]interface{}) string {
		ents := entities(d)
		out := "from fastapi import APIRouter\nfrom src.api.models import *\n\nrouter = APIRouter()\n\n"
		if len(ents) == 0 {
			return out + "@router.get(\"/items\")\nasync def list_items():\n    return {\"items\": [], \"count\": 0}\n"
		}
		for _, e := range ents {
			u := strings.Title(e)
			out += fmt.Sprintf("@router.get(\"/%ss\")\nasync def list_%ss():\n    return {\"items\": [], \"count\": 0}\n\n", e, e)
			out += fmt.Sprintf("@router.post(\"/%ss\", status_code=201)\nasync def create_%s(item: %sCreate):\n    return {\"id\": \"new-id\", **item.model_dump()}\n\n", e, e, u)
		}
		return out
	},

	"python_models": func(d map[string]interface{}) string {
		ents := entities(d)
		out := "from pydantic import BaseModel\nfrom typing import Optional\nfrom datetime import datetime\n\n"
		if len(ents) == 0 {
			return out + "class ItemBase(BaseModel):\n    name: str\n    description: Optional[str] = None\n\nclass ItemCreate(ItemBase):\n    pass\n\nclass Item(ItemBase):\n    id: str\n"
		}
		for _, e := range ents {
			u := strings.Title(e)
			out += fmt.Sprintf("class %sBase(BaseModel):\n    name: str\n\nclass %sCreate(%sBase):\n    pass\n\nclass %s(%sBase):\n    id: str\n\n", u, u, u, u, u)
		}
		return out
	},

	"python_database": func(d map[string]interface{}) string {
		return "from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession\nfrom sqlalchemy.orm import declarative_base, sessionmaker\nimport os\n\nDATABASE_URL = os.getenv(\"DATABASE_URL\", \"sqlite+aiosqlite:///./app.db\")\nengine = create_async_engine(DATABASE_URL)\nAsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)\nBase = declarative_base()\n\nasync def init_db():\n    async with engine.begin() as conn:\n        await conn.run_sync(Base.metadata.create_all)\n\nasync def get_db():\n    async with AsyncSessionLocal() as session:\n        yield session\n"
	},

	"python_auth_jwt": func(d map[string]interface{}) string {
		return "from fastapi import APIRouter, Depends, HTTPException, status\nfrom fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm\nfrom jose import JWTError, jwt\nfrom passlib.context import CryptContext\nfrom datetime import datetime, timedelta\nimport os\n\nSECRET_KEY = os.getenv(\"SECRET_KEY\", \"nexus-secret\")\nALGORITHM = \"HS256\"\noauth2_scheme = OAuth2PasswordBearer(tokenUrl=\"token\")\nauth_router = APIRouter(prefix=\"/auth\", tags=[\"auth\"])\n\ndef create_access_token(data: dict):\n    to_encode = data.copy()\n    to_encode[\"exp\"] = datetime.utcnow() + timedelta(minutes=30)\n    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)\n\n@auth_router.post(\"/token\")\nasync def login(form_data: OAuth2PasswordRequestForm = Depends()):\n    return {\"access_token\": create_access_token({\"sub\": form_data.username}), \"token_type\": \"bearer\"}\n\n@auth_router.get(\"/me\")\nasync def me(token: str = Depends(oauth2_scheme)):\n    try:\n        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])\n        return {\"username\": payload.get(\"sub\")}\n    except JWTError:\n        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED)\n"
	},

	"python_tests": func(d map[string]interface{}) string {
		return "import pytest\nfrom httpx import AsyncClient, ASGITransport\nfrom main import app\n\n@pytest.mark.asyncio\nasync def test_health():\n    async with AsyncClient(transport=ASGITransport(app=app), base_url=\"http://test\") as client:\n        response = await client.get(\"/health\")\n    assert response.status_code == 200\n    assert response.json()[\"status\"] == \"ok\"\n"
	},

	"dockerfile_python": func(d map[string]interface{}) string {
		return "FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n"
	},

	"go_main": func(d map[string]interface{}) string {
		name := appName(d)
		var sb strings.Builder
		sb.WriteString("package main\n\nimport (\n\t\"log\"\n\t\"net/http\"\n\t\"os\"\n)\n\n")
		sb.WriteString("func main() {\n")
		sb.WriteString("\tport := os.Getenv(\"PORT\")\n")
		sb.WriteString("\tif port == \"\" { port = \"8080\" }\n")
		sb.WriteString("\tmux := http.NewServeMux()\n")
		sb.WriteString("\tmux.HandleFunc(\"/health\", func(w http.ResponseWriter, r *http.Request) {\n")
		sb.WriteString("\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		sb.WriteString("\t\tw.Write([]byte(`{\"status\":\"ok\",\"app\":\"" + name + "\"}`))" + "\n")
		sb.WriteString("\t})\n")
		sb.WriteString("\tlog.Println(\"" + name + " listening on :\" + port)\n")
		sb.WriteString("\tif err := http.ListenAndServe(\":\"+port, mux); err != nil { log.Fatal(err) }\n")
		sb.WriteString("}\n")
		return sb.String()
	},

	"go_mod": func(d map[string]interface{}) string {
		return fmt.Sprintf("module github.com/nexus/%s\n\ngo 1.23.0\n", toLower(appName(d)))
	},

	"go_server": func(d map[string]interface{}) string {
		return "package api\n\nimport \"net/http\"\n\ntype Server struct{ mux *http.ServeMux }\n\nfunc NewServer() *Server {\n\ts := &Server{mux: http.NewServeMux()}\n\ts.routes()\n\treturn s\n}\n\nfunc (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) { s.mux.ServeHTTP(w, r) }\n"
	},

	"go_routes": func(d map[string]interface{}) string {
		return "package api\n\nfunc (s *Server) routes() {\n\ts.mux.HandleFunc(\"GET /health\", s.handleHealth)\n\ts.mux.HandleFunc(\"GET /api/v1/items\", s.handleListItems)\n\ts.mux.HandleFunc(\"POST /api/v1/items\", s.handleCreateItem)\n}\n"
	},

	"go_handlers": func(d map[string]interface{}) string {
		return "package api\n\nimport (\n\t\"encoding/json\"\n\t\"net/http\"\n)\n\nfunc (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {\n\tjson.NewEncoder(w).Encode(map[string]string{\"status\": \"ok\"})\n}\n\nfunc (s *Server) handleListItems(w http.ResponseWriter, r *http.Request) {\n\tjson.NewEncoder(w).Encode(map[string]interface{}{\"items\": []any{}, \"count\": 0})\n}\n\nfunc (s *Server) handleCreateItem(w http.ResponseWriter, r *http.Request) {\n\tvar item map[string]interface{}\n\tjson.NewDecoder(r.Body).Decode(&item)\n\titem[\"id\"] = \"new-id\"\n\tw.WriteHeader(http.StatusCreated)\n\tjson.NewEncoder(w).Encode(item)\n}\n"
	},

	"go_db": func(d map[string]interface{}) string {
		return "package db\n\nimport (\n\t\"database/sql\"\n\t_ \"github.com/mattn/go-sqlite3\"\n)\n\nfunc Open(path string) (*sql.DB, error) {\n\treturn sql.Open(\"sqlite3\", path)\n}\n"
	},

	"go_makefile": func(d map[string]interface{}) string {
		name := toLower(appName(d))
		return fmt.Sprintf(".PHONY: build run test clean\n\nbuild:\n\tgo build -o bin/%s ./...\n\nrun:\n\tgo run ./...\n\ntest:\n\tgo test ./... -v\n\nclean:\n\trm -rf bin/\n", name)
	},

	"dockerfile_go": func(d map[string]interface{}) string {
		name := toLower(appName(d))
		return fmt.Sprintf("FROM golang:1.23-alpine AS builder\nWORKDIR /app\nCOPY go.mod ./\nRUN go mod download\nCOPY . .\nRUN go build -o bin/%s ./...\n\nFROM alpine:3.19\nWORKDIR /app\nCOPY --from=builder /app/bin/%s .\nEXPOSE 8080\nCMD [\"./%s\"]\n", name, name, name)
	},

	"go_cli_main": func(d map[string]interface{}) string {
		return fmt.Sprintf("package main\n\nimport \"github.com/nexus/%s/cmd\"\n\nfunc main() { cmd.Execute() }\n", toLower(appName(d)))
	},

	"go_cli_root": func(d map[string]interface{}) string {
		name := toLower(appName(d))
		return fmt.Sprintf("package cmd\n\nimport (\n\t\"fmt\"\n\t\"os\"\n\t\"github.com/spf13/cobra\"\n)\n\nvar rootCmd = &cobra.Command{\n\tUse:\"%s\",\n\tShort:\"%s\",\n}\n\nfunc Execute() {\n\tif err := rootCmd.Execute(); err != nil {\n\t\tfmt.Fprintln(os.Stderr, err)\n\t\tos.Exit(1)\n\t}\n}\n", name, appName(d))
	},

	"go_cli_version": func(d map[string]interface{}) string {
		return fmt.Sprintf("package cmd\n\nimport (\n\t\"fmt\"\n\t\"github.com/spf13/cobra\"\n)\n\nvar versionCmd = &cobra.Command{\n\tUse:\"version\",\n\tShort:\"Print the version\",\n\tRun: func(cmd *cobra.Command, args []string) { fmt.Println(\"%s v1.0.0\") },\n}\n\nfunc init() { rootCmd.AddCommand(versionCmd) }\n", appName(d))
	},

	"react_package_json": func(d map[string]interface{}) string {
		name := toLower(appName(d))
		return fmt.Sprintf("{\n  \"name\": \"%s\",\n  \"version\": \"1.0.0\",\n  \"type\": \"module\",\n  \"scripts\": { \"dev\": \"vite\", \"build\": \"tsc -b && vite build\" },\n  \"dependencies\": { \"react\": \"^18.3.1\", \"react-dom\": \"^18.3.1\", \"react-router-dom\": \"^6.23.0\" },\n  \"devDependencies\": { \"@vitejs/plugin-react\": \"^4.3.0\", \"typescript\": \"^5.5.3\", \"vite\": \"^5.4.0\" }\n}\n", name)
	},

	"react_vite_config": func(d map[string]interface{}) string {
		return "import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({ plugins: [react()], server: { port: 3000 } })\n"
	},

	"react_index_html": func(d map[string]interface{}) string {
		return fmt.Sprintf("<!doctype html>\n<html>\n  <head><meta charset=\"UTF-8\" /><title>%s</title></head>\n  <body><div id=\"root\"></div><script type=\"module\" src=\"/src/main.tsx\"></script></body>\n</html>\n", appName(d))
	},

	"react_main": func(d map[string]interface{}) string {
		return "import { StrictMode } from 'react'\nimport { createRoot } from 'react-dom/client'\nimport './index.css'\nimport App from './App'\n\ncreateRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)\n"
	},

	"react_app": func(d map[string]interface{}) string {
		return "import { BrowserRouter, Routes, Route } from 'react-router-dom'\nimport Layout from './components/Layout'\nimport HomePage from './pages/HomePage'\n\nexport default function App() {\n  return (\n    <BrowserRouter><Routes><Route path=\"/\" element={<Layout />}><Route index element={<HomePage />} /></Route></Routes></BrowserRouter>\n  )\n}\n"
	},

	"react_css": func(d map[string]interface{}) string {
		return "* { box-sizing: border-box; margin: 0; padding: 0; }\nbody { font-family: system-ui, sans-serif; }\n"
	},

	"react_homepage": func(d map[string]interface{}) string {
		return fmt.Sprintf("export default function HomePage() {\n  return <div style={{padding:'2rem'}}><h1>%s</h1><p>%s</p></div>\n}\n", appName(d), desc(d))
	},

	"react_layout": func(d map[string]interface{}) string {
		return fmt.Sprintf("import { Outlet } from 'react-router-dom'\nexport default function Layout() {\n  return <div><header style={{padding:'1rem'}}><strong>%s</strong></header><main><Outlet /></main></div>\n}\n", appName(d))
	},

	"react_tsconfig": func(d map[string]interface{}) string {
		return "{\"compilerOptions\":{\"target\":\"ES2020\",\"lib\":[\"ES2020\",\"DOM\"],\"module\":\"ESNext\",\"moduleResolution\":\"bundler\",\"jsx\":\"react-jsx\",\"strict\":true,\"noEmit\":true,\"skipLibCheck\":true},\"include\":[\"src\"]}\n"
	},

	"kotlin_settings": func(d map[string]interface{}) string {
		return fmt.Sprintf("pluginManagement {\n    repositories { google(); mavenCentral(); gradlePluginPortal() }\n}\nrootProject.name = \"%s\"\ninclude(\":app\")\n", toLower(appName(d)))
	},

	"kotlin_root_build": func(d map[string]interface{}) string {
		return "plugins {\n    alias(libs.plugins.android.application) apply false\n    alias(libs.plugins.kotlin.android) apply false\n}\n"
	},

	"kotlin_app_build": func(d map[string]interface{}) string {
		p := pkg(d)
		return fmt.Sprintf("plugins {\n    alias(libs.plugins.android.application)\n    alias(libs.plugins.kotlin.android)\n}\n\nandroid {\n    namespace = \"%s\"\n    compileSdk = 35\n    defaultConfig { applicationId = \"%s\"; minSdk = 24; targetSdk = 35; versionCode = 1; versionName = \"1.0\" }\n    buildFeatures { compose = true }\n}\n\ndependencies {\n    implementation(libs.androidx.core.ktx)\n    implementation(libs.androidx.activity.compose)\n    implementation(libs.androidx.material3)\n}\n", p, p)
	},

	"kotlin_manifest": func(d map[string]interface{}) string {
		var sb strings.Builder
		sb.WriteString("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
		sb.WriteString("<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n")
		sb.WriteString("    <application android:label=\"" + appName(d) + "\" android:theme=\"@style/Theme.Material3.DayNight\">\n")
		sb.WriteString("        <activity android:name=\".MainActivity\" android:exported=\"true\">\n")
		sb.WriteString("            <intent-filter>\n")
		sb.WriteString("                <action android:name=\"android.intent.action.MAIN\"/>\n")
		sb.WriteString("                <category android:name=\"android.intent.category.LAUNCHER\"/>\n")
		sb.WriteString("            </intent-filter>\n")
		sb.WriteString("        </activity>\n")
		sb.WriteString("    </application>\n")
		sb.WriteString("</manifest>\n")
		return sb.String()
	},

	"kotlin_main_activity": func(d map[string]interface{}) string {
		p := pkg(d)
		return fmt.Sprintf("package %s\n\nimport android.os.Bundle\nimport androidx.activity.ComponentActivity\nimport androidx.activity.compose.setContent\nimport %s.ui.HomeScreen\nimport %s.ui.theme.AppTheme\n\nclass MainActivity : ComponentActivity() {\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContent { AppTheme { HomeScreen() } }\n    }\n}\n", p, p, p)
	},

	"kotlin_home_screen": func(d map[string]interface{}) string {
		p := pkg(d)
		return fmt.Sprintf("package %s.ui\n\nimport androidx.compose.foundation.layout.*\nimport androidx.compose.material3.*\nimport androidx.compose.runtime.Composable\nimport androidx.compose.ui.Alignment\nimport androidx.compose.ui.Modifier\nimport androidx.compose.ui.unit.dp\n\n@Composable\nfun HomeScreen() {\n    Scaffold { padding ->\n        Column(modifier = Modifier.fillMaxSize().padding(padding).padding(16.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) {\n            Text(\"%s\", style = MaterialTheme.typography.headlineMedium)\n            Spacer(Modifier.height(8.dp))\n            Text(\"%s\", style = MaterialTheme.typography.bodyMedium)\n        }\n    }\n}\n", p, appName(d), desc(d))
	},

	"kotlin_theme": func(d map[string]interface{}) string {
		return fmt.Sprintf("package %s.ui.theme\n\nimport androidx.compose.material3.MaterialTheme\nimport androidx.compose.runtime.Composable\n\n@Composable\nfun AppTheme(content: @Composable () -> Unit) { MaterialTheme(content = content) }\n", pkg(d))
	},

	"flutter_pubspec": func(d map[string]interface{}) string {
		return fmt.Sprintf("name: %s\ndescription: %s\nversion: 1.0.0+1\n\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\n\ndependencies:\n  flutter:\n    sdk: flutter\n  provider: ^6.1.0\n\ndev_dependencies:\n  flutter_test:\n    sdk: flutter\n\nflutter:\n  uses-material-design: true\n", toLower(appName(d)), desc(d))
	},

	"flutter_main": func(d map[string]interface{}) string {
		return "import 'package:flutter/material.dart';\nimport 'app.dart';\n\nvoid main() { runApp(const MyApp()); }\n"
	},

	"flutter_app": func(d map[string]interface{}) string {
		return fmt.Sprintf("import 'package:flutter/material.dart';\nimport 'screens/home_screen.dart';\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n  @override\n  Widget build(BuildContext context) => MaterialApp(title: '%s', theme: ThemeData(useMaterial3: true), home: const HomeScreen());\n}\n", appName(d))
	},

	"flutter_home": func(d map[string]interface{}) string {
		return fmt.Sprintf("import 'package:flutter/material.dart';\n\nclass HomeScreen extends StatelessWidget {\n  const HomeScreen({super.key});\n  @override\n  Widget build(BuildContext context) => Scaffold(\n    appBar: AppBar(title: const Text('%s')),\n    body: Center(child: Text('%s')),\n  );\n}\n", appName(d), desc(d))
	},

	"flutter_appbar": func(d map[string]interface{}) string {
		return "import 'package:flutter/material.dart';\n\nclass AppBarWidget extends StatelessWidget implements PreferredSizeWidget {\n  const AppBarWidget({super.key, required this.title});\n  final String title;\n  @override\n  Widget build(BuildContext context) => AppBar(title: Text(title));\n  @override\n  Size get preferredSize => const Size.fromHeight(kToolbarHeight);\n}\n"
	},
}
